import { Montserrat } from 'next/font/google';
import Footer from './components/Footer';
import Navbar from './components/Navbar';
import './globals.css';

const mainFont = Montserrat({ subsets: ['latin'] });

export const metadata = {
    title: 'CINEMON',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang='en'>
            <body
                className={`${mainFont.className} mx-auto max-w-screen-xl bg-slate-900 text-white`}
            >
                <Navbar />
                {children}
                <Footer />
            </body>
        </html>
    );
}
