export const appKeywords = [
    'movies',
    'film',
    'cinema',
    'actors',
    'actresses',
    'director',
    'genre',
    'reviews',
    'trailers',
    'upcoming',
    'classics',
    'blockbusters',
    'award-winning',
    'Hollywood',
    'international',
    'indie',
    'streaming',
    'watch online',
    'filmography',
    'box office',
    'movie news',
    'film industry',
    'movie ratings',
    'top-rated',
    'movie database',
    'filmography',
    'movie recommendations',
    'film festivals',
    'movie releases',
    'celebrities',
    'red carpet',
    'movie trivia',
    'cinematic universe',
    'movie quotes',
    'film analysis',
    'movie posters',
    'behind the scenes',
    'cinematography',
    'film soundtracks',
    'movie merchandise',
    'film reviews',
    'movie premieres',
    'cult classics',
    'film history',
    'action movies',
    'romantic movies',
    'comedy movies',
    'sci-fi movies',
    'drama movies',
    'horror movies',
];
